import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/shared/**/*.{js,ts,jsx,tsx,mdx}',
    './src/entities/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
    './src/widgets/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Design tokens из tokens.json
        brand: {
          primary: 'hsl(var(--color-brand-primary))',
          'primary-hover': 'hsl(var(--color-brand-primary-hover))',
          'primary-active': 'hsl(var(--color-brand-primary-active))',
          secondary: 'hsl(var(--color-brand-secondary))',
          accent: 'hsl(var(--color-brand-accent))',
        },
        bg: {
          default: 'hsl(var(--color-bg-default))',
          surface: 'hsl(var(--color-bg-surface))',
          elevated: 'hsl(var(--color-bg-elevated))',
          hover: 'hsl(var(--color-bg-hover))',
          selected: 'hsl(var(--color-bg-selected))',
        },
        text: {
          primary: 'hsl(var(--color-text-primary))',
          secondary: 'hsl(var(--color-text-secondary))',
          tertiary: 'hsl(var(--color-text-tertiary))',
          inverse: 'hsl(var(--color-text-inverse))',
          disabled: 'hsl(var(--color-text-disabled))',
        },
        border: {
          DEFAULT: 'hsl(var(--color-border-default))',
          default: 'hsl(var(--color-border-default))',
          strong: 'hsl(var(--color-border-strong))',
          focus: 'hsl(var(--color-border-focus))',
        },
        divider: 'hsl(var(--color-divider))',
        icon: {
          primary: 'hsl(var(--color-icon-primary))',
          secondary: 'hsl(var(--color-icon-secondary))',
        },
        state: {
          success: 'hsl(var(--color-state-success))',
          'success-bg': 'hsl(var(--color-state-success-bg))',
          warning: 'hsl(var(--color-state-warning))',
          'warning-bg': 'hsl(var(--color-state-warning-bg))',
          error: 'hsl(var(--color-state-error))',
          'error-bg': 'hsl(var(--color-state-error-bg))',
          info: 'hsl(var(--color-state-info))',
          'info-bg': 'hsl(var(--color-state-info-bg))',
        },
        status: {
          new: 'hsl(var(--color-status-new))',
          'in-progress': 'hsl(var(--color-status-in-progress))',
          closed: 'hsl(var(--color-status-closed))',
          draft: 'hsl(var(--color-status-draft))',
          submitted: 'hsl(var(--color-status-submitted))',
          overdue: 'hsl(var(--color-status-overdue))',
          pending: 'hsl(var(--color-status-pending))',
          accepted: 'hsl(var(--color-status-accepted))',
          declined: 'hsl(var(--color-status-declined))',
          expired: 'hsl(var(--color-status-expired))',
          canceled: 'hsl(var(--color-status-canceled))',
        },
        link: {
          default: 'hsl(var(--color-link-default))',
          hover: 'hsl(var(--color-link-hover))',
        },
        'focus-ring': 'hsl(var(--color-focus-ring))',
        'overlay-scrim': 'var(--color-overlay-scrim)',
        'shadow-color': 'var(--color-shadow-color)',
      },
      spacing: {
        m: 'var(--spacing-m)',
        m2: 'var(--spacing-m2)',
        m3: 'var(--spacing-m3)',
        m4: 'var(--spacing-m4)',
        m5: 'var(--spacing-m5)',
        m6: 'var(--spacing-m6)',
        m7: 'var(--spacing-m7)',
        m8: 'var(--spacing-m8)',
        m9: 'var(--spacing-m9)',
        m10: 'var(--spacing-m10)',
        m11: 'var(--spacing-m11)',
        m12: 'var(--spacing-m12)',
        m13: 'var(--spacing-m13)',
        m14: 'var(--spacing-m14)',
        m15: 'var(--spacing-m15)',
        m16: 'var(--spacing-m16)',
        m17: 'var(--spacing-m17)',
        m18: 'var(--spacing-m18)',
        m19: 'var(--spacing-m19)',
        m20: 'var(--spacing-m20)',
        m21: 'var(--spacing-m21)',
        m22: 'var(--spacing-m22)',
        m23: 'var(--spacing-m23)',
        m24: 'var(--spacing-m24)',
        m25: 'var(--spacing-m25)',
        m26: 'var(--spacing-m26)',
        m27: 'var(--spacing-m27)',
        m28: 'var(--spacing-m28)',
        m29: 'var(--spacing-m29)',
        m30: 'var(--spacing-m30)',
        m31: 'var(--spacing-m31)',
        m32: 'var(--spacing-m32)',
      },
      borderRadius: {
        lg: '0.5rem',
        md: 'calc(0.5rem - 2px)',
        sm: 'calc(0.5rem - 4px)',
      },
      fontFamily: {
        sans: ['var(--typography-display-2xl-font-family)', 'sans-serif'],
        mono: ['var(--typography-code-sm-font-family)', 'monospace'],
      },
    },
  },
  plugins: [
    function ({ addUtilities }: { addUtilities: any }) {
      const typographyUtilities: Record<string, any> = {
        // Display
        '.typography-display-2xl': {
          fontFamily: 'var(--typography-display-2xl-font-family)',
          fontWeight: 'var(--typography-display-2xl-font-weight)',
          fontSize: 'var(--typography-display-2xl-font-size)',
          lineHeight: 'var(--typography-display-2xl-line-height)',
          letterSpacing: 'var(--typography-display-2xl-letter-spacing)',
        },
        '.typography-display-xl': {
          fontFamily: 'var(--typography-display-xl-font-family)',
          fontWeight: 'var(--typography-display-xl-font-weight)',
          fontSize: 'var(--typography-display-xl-font-size)',
          lineHeight: 'var(--typography-display-xl-line-height)',
          letterSpacing: 'var(--typography-display-xl-letter-spacing)',
        },
        // Heading
        '.typography-heading-lg': {
          fontFamily: 'var(--typography-heading-lg-font-family)',
          fontWeight: 'var(--typography-heading-lg-font-weight)',
          fontSize: 'var(--typography-heading-lg-font-size)',
          lineHeight: 'var(--typography-heading-lg-line-height)',
          letterSpacing: 'var(--typography-heading-lg-letter-spacing)',
        },
        '.typography-heading-md': {
          fontFamily: 'var(--typography-heading-md-font-family)',
          fontWeight: 'var(--typography-heading-md-font-weight)',
          fontSize: 'var(--typography-heading-md-font-size)',
          lineHeight: 'var(--typography-heading-md-line-height)',
          letterSpacing: 'var(--typography-heading-md-letter-spacing)',
        },
        '.typography-heading-sm': {
          fontFamily: 'var(--typography-heading-sm-font-family)',
          fontWeight: 'var(--typography-heading-sm-font-weight)',
          fontSize: 'var(--typography-heading-sm-font-size)',
          lineHeight: 'var(--typography-heading-sm-line-height)',
          letterSpacing: 'var(--typography-heading-sm-letter-spacing)',
        },
        // Title
        '.typography-title-lg': {
          fontFamily: 'var(--typography-title-lg-font-family)',
          fontWeight: 'var(--typography-title-lg-font-weight)',
          fontSize: 'var(--typography-title-lg-font-size)',
          lineHeight: 'var(--typography-title-lg-line-height)',
          letterSpacing: 'var(--typography-title-lg-letter-spacing)',
        },
        '.typography-title-md': {
          fontFamily: 'var(--typography-title-md-font-family)',
          fontWeight: 'var(--typography-title-md-font-weight)',
          fontSize: 'var(--typography-title-md-font-size)',
          lineHeight: 'var(--typography-title-md-line-height)',
          letterSpacing: 'var(--typography-title-md-letter-spacing)',
        },
        '.typography-title-sm': {
          fontFamily: 'var(--typography-title-sm-font-family)',
          fontWeight: 'var(--typography-title-sm-font-weight)',
          fontSize: 'var(--typography-title-sm-font-size)',
          lineHeight: 'var(--typography-title-sm-line-height)',
          letterSpacing: 'var(--typography-title-sm-letter-spacing)',
        },
        // Body
        '.typography-body-lg-regular': {
          fontFamily: 'var(--typography-body-lg-regular-font-family)',
          fontWeight: 'var(--typography-body-lg-regular-font-weight)',
          fontSize: 'var(--typography-body-lg-regular-font-size)',
          lineHeight: 'var(--typography-body-lg-regular-line-height)',
          letterSpacing: 'var(--typography-body-lg-regular-letter-spacing)',
        },
        '.typography-body-lg-medium': {
          fontFamily: 'var(--typography-body-lg-medium-font-family)',
          fontWeight: 'var(--typography-body-lg-medium-font-weight)',
          fontSize: 'var(--typography-body-lg-medium-font-size)',
          lineHeight: 'var(--typography-body-lg-medium-line-height)',
          letterSpacing: 'var(--typography-body-lg-medium-letter-spacing)',
        },
        '.typography-body-md-regular': {
          fontFamily: 'var(--typography-body-md-regular-font-family)',
          fontWeight: 'var(--typography-body-md-regular-font-weight)',
          fontSize: 'var(--typography-body-md-regular-font-size)',
          lineHeight: 'var(--typography-body-md-regular-line-height)',
          letterSpacing: 'var(--typography-body-md-regular-letter-spacing)',
        },
        '.typography-body-md-medium': {
          fontFamily: 'var(--typography-body-md-medium-font-family)',
          fontWeight: 'var(--typography-body-md-medium-font-weight)',
          fontSize: 'var(--typography-body-md-medium-font-size)',
          lineHeight: 'var(--typography-body-md-medium-line-height)',
          letterSpacing: 'var(--typography-body-md-medium-letter-spacing)',
        },
        '.typography-body-sm-regular': {
          fontFamily: 'var(--typography-body-sm-regular-font-family)',
          fontWeight: 'var(--typography-body-sm-regular-font-weight)',
          fontSize: 'var(--typography-body-sm-regular-font-size)',
          lineHeight: 'var(--typography-body-sm-regular-line-height)',
          letterSpacing: 'var(--typography-body-sm-regular-letter-spacing)',
        },
        '.typography-body-sm-medium': {
          fontFamily: 'var(--typography-body-sm-medium-font-family)',
          fontWeight: 'var(--typography-body-sm-medium-font-weight)',
          fontSize: 'var(--typography-body-sm-medium-font-size)',
          lineHeight: 'var(--typography-body-sm-medium-line-height)',
          letterSpacing: 'var(--typography-body-sm-medium-letter-spacing)',
        },
        // Label
        '.typography-label-lg': {
          fontFamily: 'var(--typography-label-lg-font-family)',
          fontWeight: 'var(--typography-label-lg-font-weight)',
          fontSize: 'var(--typography-label-lg-font-size)',
          lineHeight: 'var(--typography-label-lg-line-height)',
          letterSpacing: 'var(--typography-label-lg-letter-spacing)',
        },
        '.typography-label-md': {
          fontFamily: 'var(--typography-label-md-font-family)',
          fontWeight: 'var(--typography-label-md-font-weight)',
          fontSize: 'var(--typography-label-md-font-size)',
          lineHeight: 'var(--typography-label-md-line-height)',
          letterSpacing: 'var(--typography-label-md-letter-spacing)',
        },
        '.typography-label-sm': {
          fontFamily: 'var(--typography-label-sm-font-family)',
          fontWeight: 'var(--typography-label-sm-font-weight)',
          fontSize: 'var(--typography-label-sm-font-size)',
          lineHeight: 'var(--typography-label-sm-line-height)',
          letterSpacing: 'var(--typography-label-sm-letter-spacing)',
        },
        '.typography-label-xs': {
          fontFamily: 'var(--typography-label-xs-font-family)',
          fontWeight: 'var(--typography-label-xs-font-weight)',
          fontSize: 'var(--typography-label-xs-font-size)',
          lineHeight: 'var(--typography-label-xs-line-height)',
          letterSpacing: 'var(--typography-label-xs-letter-spacing)',
        },
        // Caption
        '.typography-caption-sm-regular': {
          fontFamily: 'var(--typography-caption-sm-regular-font-family)',
          fontWeight: 'var(--typography-caption-sm-regular-font-weight)',
          fontSize: 'var(--typography-caption-sm-regular-font-size)',
          lineHeight: 'var(--typography-caption-sm-regular-line-height)',
          letterSpacing: 'var(--typography-caption-sm-regular-letter-spacing)',
        },
        '.typography-caption-sm-medium': {
          fontFamily: 'var(--typography-caption-sm-medium-font-family)',
          fontWeight: 'var(--typography-caption-sm-medium-font-weight)',
          fontSize: 'var(--typography-caption-sm-medium-font-size)',
          lineHeight: 'var(--typography-caption-sm-medium-line-height)',
          letterSpacing: 'var(--typography-caption-sm-medium-letter-spacing)',
        },
        '.typography-caption-xs': {
          fontFamily: 'var(--typography-caption-xs-font-family)',
          fontWeight: 'var(--typography-caption-xs-font-weight)',
          fontSize: 'var(--typography-caption-xs-font-size)',
          lineHeight: 'var(--typography-caption-xs-line-height)',
          letterSpacing: 'var(--typography-caption-xs-letter-spacing)',
        },
        // Overline
        '.typography-overline-xs': {
          fontFamily: 'var(--typography-overline-xs-font-family)',
          fontWeight: 'var(--typography-overline-xs-font-weight)',
          fontSize: 'var(--typography-overline-xs-font-size)',
          lineHeight: 'var(--typography-overline-xs-line-height)',
          letterSpacing: 'var(--typography-overline-xs-letter-spacing)',
          textTransform: 'var(--typography-overline-xs-text-transform)',
        },
        // Code
        '.typography-code-sm': {
          fontFamily: 'var(--typography-code-sm-font-family)',
          fontWeight: 'var(--typography-code-sm-font-weight)',
          fontSize: 'var(--typography-code-sm-font-size)',
          lineHeight: 'var(--typography-code-sm-line-height)',
          letterSpacing: 'var(--typography-code-sm-letter-spacing)',
        },
      }
      addUtilities(typographyUtilities)
    },
  ],
}
export default config
